FROM python:3.10-alpine as builder

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

COPY . .

RUN pip install --upgrade pip && \
    pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/app/wheels -r requirements.txt

FROM python:3.10-alpine

RUN mkdir -p /home/app && \
    addgroup -S app && adduser -S app -G app

ENV HOME=/home/app
ENV APP_HOME=/home/app/web

RUN mkdir $APP_HOME && \
    mkdir $APP_HOME/staticfiles && \
    mkdir $APP_HOME/media && \
    apk update && apk add libpq

WORKDIR $APP_HOME

COPY --from=builder /usr/src/app/wheels /wheels
COPY --from=builder /usr/src/app/requirements.txt .

COPY . $APP_HOME

RUN pip install --no-cache /wheels/* && \
    chown -R app:app $APP_HOME

USER app

RUN ["chmod", "+x", "/home/app/web/docker_alpine/entrypoint-prod-alpine.sh"]

ENTRYPOINT ["/home/app/web/docker_alpine/entrypoint-prod-alpine.sh"]
