# Generated by Django 4.1 on 2022-08-31 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_list',
            new_name='products',
        ),
    ]
