FROM python:3.10-alpine

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

COPY . .

RUN pip install --upgrade pip && \
     pip install -r requirements.txt

RUN ["chmod", "+x", "/usr/src/app/docker_alpine/entrypoint-alpine.sh"]

ENTRYPOINT ["sh", "/usr/src/app/docker_alpine/entrypoint-alpine.sh"]
