version: "3"

services:
  web:
    build:
      context: ./
      dockerfile: deployment/docker_alpine/Dockerfile-alpine
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - env_project/dev/.env.dev
    volumes:
      - line_story_drf_alpine:/usr/src/app
    depends_on:
      - db

  redis:
    image: redis:alpine
    depends_on:
      - web

  db:
    image: postgres:alpine
    env_file:
      - env_project/dev/.env.dev.db
    volumes:
      - line_story_drf_postgres_data_alpine:/var/lib/postgresql/data

  celery:
    build:
      context: ./
      dockerfile: deployment/docker_alpine/Dockerfile-alpine
    command: celery -A line_story_drf worker -l info
    volumes:
      - line_story_drf_celery_alpine_data:/usr/src/app
    env_file:
      - env_project/dev/.env.dev
    depends_on:
      - redis

volumes:
  line_story_drf_alpine:
  line_story_drf_postgres_data_alpine:
  line_story_drf_celery_alpine_data:
