version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: docker_alpine/Dockerfile-prod-alpine
    command: gunicorn line_story_drf.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume_prod_alpine:/home/app/web/staticfiles
      - static_media_prod_alpine:/home/app/web/media
    env_file:
      - env_project/prod/.env.prod
    depends_on:
      - db

  db:
    image: postgres:alpine
    env_file:
      - env_project/prod/.env.prod.db
    volumes:
      - line_story_drf_postgres_data_prod_alpine:/var/lib/postgresql/data/

  nginx:
    build:
      context: ./
      dockerfile: nginx_alpine/Dockerfile-alpine
    ports:
      - "1337:80"
    volumes:
      - static_volume_prod_alpine:/home/app/web/staticfiles
      - static_media_prod_alpine:/home/app/web/media
    depends_on:
      - web

  redis:
    image: redis:alpine
    depends_on:
      - web

  celery:
    build:
      context: ./
      dockerfile: docker_alpine/Dockerfile-prod-alpine
    command: >
      sh -c "celery -A line_story_drf worker -l info"
    volumes:
      - line_story_drf_celery_data_prod_alpine:/home/app/web
    env_file:
      - env_project/prod/.env.prod
    depends_on:
      - redis

volumes:
  line_story_drf_postgres_data_prod_alpine:
  line_story_drf_celery_data_prod_alpine:
  static_volume_prod_alpine:
  static_media_prod_alpine:
