version: "3"

services:
  web:
    build:
      context: ./
      dockerfile: docker_alpine/Dockerfile-alpine
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.alpine
    volumes:
      - line_story_drf_alpine:/usr/src/app
    depends_on:
      - db

  redis:
    image: redis:alpine
    depends_on:
      - web

  db:
    image: postgres:alpine
    env_file:
      - ./.env.db
    volumes:
      - line_story_drf_postgres_data_alpine:/var/lib/postgresql/data

  celery:
    build:
      context: ./
      dockerfile: docker_alpine/Dockerfile-alpine
    command: >
      sh -c "celery -A line_story_drf worker -l info"
    volumes:
      - line_story_drf_celery_data_alpine:/usr/src/app
    env_file:
      - ./.env.alpine
    depends_on:
      - redis

volumes:
  line_story_drf_alpine:
  line_story_drf_postgres_data_alpine:
  line_story_drf_celery_data_alpine:
