version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile-prod
    command: gunicorn line_story_drf.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume_prod:/home/app/web/staticfiles
      - static_media_prod:/home/app/web/media
    env_file:
      - env_project/prod/.env.prod
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - env_project/prod/.env.prod.db
    volumes:
      - line_story_drf_postgres_data_prod:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - static_volume_prod:/home/app/web/staticfiles
      - static_media_prod:/home/app/web/media
    depends_on:
      - web

  redis:
    image: redis
    depends_on:
      - web

  celery:
    build:
      context: ./
      dockerfile: Dockerfile-prod
    command: celery -A line_story_drf worker -l info
    volumes:
      - line_story_drf_celery_data_prod:/usr/src/line_story_drf
    env_file:
      - env_project/prod/.env.prod
    depends_on:
      - db
      - redis

volumes:
  line_story_drf_postgres_data_prod:
  line_story_drf_celery_data_prod:
  static_volume_prod:
  static_media_prod:
