# Generated by Django 4.1 on 2022-09-29 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='country')),
                ('reduction', models.CharField(blank=True, max_length=255, null=True, verbose_name='reduction')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='BlacklistedCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='countries.country')),
            ],
            options={
                'verbose_name': 'country in black list',
                'verbose_name_plural': 'countries in black list',
            },
        ),
    ]
